<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260928102307 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE booking_policy (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, time_from TIME(0) WITHOUT TIME ZONE NOT NULL, time_to TIME(0) WITHOUT TIME ZONE NOT NULL, cancel_before_minutes INT NOT NULL, reminder_before_minutes INT NOT NULL, business_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4BE73EE8A89DB457 ON booking_policy (business_id)');
        $this->addSql('ALTER TABLE booking_policy ADD CONSTRAINT FK_4BE73EE8A89DB457 FOREIGN KEY (business_id) REFERENCES business (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE booking_policy ADD CONSTRAINT chk_booking_policy_time_range CHECK (time_from < time_to)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE booking_policy DROP CONSTRAINT FK_4BE73EE8A89DB457');
        $this->addSql('DROP TABLE booking_policy');
    }
}
