<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260930103002 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create booking table with exclusion constraint';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE booking (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, starts_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, ends_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, status VARCHAR(255) NOT NULL, cancel_reason VARCHAR(255) DEFAULT NULL, cancel_before_minutes INT NOT NULL, reminder_before_minutes INT NOT NULL, version INT DEFAULT 1 NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, resource_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E00CEDDE89329D25 ON booking (resource_id)');
        $this->addSql('CREATE INDEX IDX_E00CEDDEA76ED395 ON booking (user_id)');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDE89329D25 FOREIGN KEY (resource_id) REFERENCES resource (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDEA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql("ALTER TABLE booking ADD CONSTRAINT chk_booking_time_range CHECK (ends_at > starts_at)");
        $this->addSql("ALTER TABLE booking ADD CONSTRAINT chk_booking_status CHECK (status IN ('booked', 'confirmed', 'cancelled', 'completed'))");
        $this->addSql("ALTER TABLE booking ADD CONSTRAINT chk_booking_cancel_reason CHECK (cancel_reason IS NULL OR cancel_reason IN ('no_show', 'user_cancelled'))");
        $this->addSql("ALTER TABLE booking ADD CONSTRAINT booking_no_overlap EXCLUDE USING gist (resource_id WITH =, tstzrange(starts_at, ends_at) WITH &&) WHERE (status IN ('booked', 'confirmed'))");
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE booking DROP CONSTRAINT FK_E00CEDDE89329D25');
        $this->addSql('ALTER TABLE booking DROP CONSTRAINT FK_E00CEDDEA76ED395');
        $this->addSql('DROP TABLE booking');
    }
}
