<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260928103605 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create resource table (single table inheritance)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE resource (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, capacity INT NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, business_id INT NOT NULL, type VARCHAR(255) NOT NULL, features JSON DEFAULT NULL, has_window_view BOOLEAN DEFAULT NULL, zone VARCHAR(100) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BC91F416A89DB457 ON resource (business_id)');
        $this->addSql('ALTER TABLE resource ADD CONSTRAINT FK_BC91F416A89DB457 FOREIGN KEY (business_id) REFERENCES business (id) NOT DEFERRABLE');
        $this->addSql("ALTER TABLE resource ADD CONSTRAINT chk_resource_type_fields CHECK (
            (type = 'meeting_room' AND features IS NOT NULL AND has_window_view IS NULL AND zone IS NULL)
            OR
            (type = 'restaurant_table' AND has_window_view IS NOT NULL AND zone IS NOT NULL AND features IS NULL)
        )");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE resource DROP CONSTRAINT FK_BC91F416A89DB457');
        $this->addSql('DROP TABLE resource');
    }
}
