<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260928092200 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE business (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, business_type VARCHAR(255) NOT NULL, default_cancel_before_minutes INT NOT NULL, default_reminder_before_minutes INT NOT NULL, timezone VARCHAR(100) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, city_id INT NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8D36E388BAC62AF ON business (city_id)');
        $this->addSql('CREATE INDEX IDX_8D36E387E3C61F9 ON business (owner_id)');
        $this->addSql('ALTER TABLE business ADD CONSTRAINT FK_8D36E388BAC62AF FOREIGN KEY (city_id) REFERENCES city (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE business ADD CONSTRAINT FK_8D36E387E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE business DROP CONSTRAINT FK_8D36E388BAC62AF');
        $this->addSql('ALTER TABLE business DROP CONSTRAINT FK_8D36E387E3C61F9');
        $this->addSql('DROP TABLE business');
    }
}
